name: score-publisher-service
host: localhost
port: 7003
dbconfig:
  host: localhost
  port: 5432
  username: postgres
  password: nirmal123
  dbname: test-db
kafka:
  broker: "localhost:9092"
  topic: "user-scores"
  groupid: "score-service-consumers"